apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagemanager-data
  namespace: eda-system
  labels:
    eda.nokia.com/app: eda-imagemanager
    eda.nokia.com/app-group: control-plane
    eda.nokia.com/component: imagemanager-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # app-set: ${uploadStorageSize}
